services:
  we-meet-coturn:
    env_file: .env
    image: coturn/coturn:4.6.3
    container_name: we-meet-coturn
    restart: unless-stopped
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "49152-49200:49152-49200/udp"
    environment:
      # Автодетект IP (работает на VPS)
      DETECT_EXTERNAL_IP: "true"
      TURN_USERNAME: "${TURN_USERNAME}"
      TURN_PASSWORD: "${TURN_PASSWORD}"
#      REALM: "${DOMAIN}"
    volumes:
      - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
      - ./coturn/coturn-data:/var/lib/coturn
      - ./coturn/coturn-logs:/var/log
      - ./ssl:/etc/coturn/ssl:ro
    networks:
      - we-meet-network

networks:
  we-meet-network:
    external: true